### ISSUE TITLE
Server closes connection immediately, no output

### ISSUE THREAD

**Issue by a-v-s** [FiloSottile/whosthere#17]
When I try to connect to the server, the server immediately closes the connection. 

```
[andre@8530w ~]$ ssh  whoami.filippo.io
Connection to whoami.filippo.io closed.
```

The log file gives the output for ssh -v
[whoami_log.txt](https://github.com/FiloSottile/whosthere/files/159817/whoami_log.txt)

**Comment by FiloSottile** [comment]
The database connection was down, fixed!
