### ISSUE TITLE
not enough arguments in call to s.githubClient.Users.Get

### ISSUE THREAD

**Issue by virtualdxs** [FiloSottile/whosthere#19]
ssh://whoami.filippo.io is down, so I'm trying to build this myself, but I got the following compile error:

     ~ > go get github.com/FiloSottile/whosthere/src/ssherver                                                                                                      
    # github.com/FiloSottile/whosthere/src/ssherver                                 
    go/src/github.com/FiloSottile/whosthere/src/ssherver/db.go:30: not enough arguments in call to s.githubClient.Users.Get
            have (string)                   
            want (context.Context, string)  
     ✘ ~ > 

I apologize if this is just go noobery but it seems like a normal compile error so I decided that's unlikely.

**Comment by FiloSottile** [comment]
Thanks for the report. This was fixed a while ago, and we now use modules so API breakages won't affect us anymore.
