### ISSUE TITLE
SSH on whoami.filippo.io refusing connection

### ISSUE THREAD

**Issue by olafz** [FiloSottile/whosthere#20]
The hosted version of this tool is refusing connections on the endpoint documented on the readme:

```
$ ssh whoami.filippo.io
ssh: connect to host whoami.filippo.io port 22: Connection refused
```

Not sure this is the place to report this as an "issue", but maybe it triggers something or somebody can confirm this no longer works.

**Comment by FiloSottile** [comment]
Fixed! Thanks for reporting it ^^
