### ISSUE TITLE
Is service down?

### ISSUE THREAD

**Issue by ad-m** [FiloSottile/whosthere#21]
Service no longer provider usernames. It looks like there is already a normal SSH server on the other side.

**Comment by wrfly** [comment]
same here:
```
Received disconnect from 74.101.204.177 port 22:2: too many authentication failures
Disconnected from 74.101.204.177 port 22
```

**Comment by FiloSottile** [comment]
Looks up to me at the moment. Please let me know if it still doesn't work for you.

**Comment by ioistired** [comment]
Same for me. Just closes the connection.
